// This file would typically be auto-generated by the Supabase CLI
// based on your database schema. For now, we'll define a placeholder.
// See: https://supabase.com/docs/guides/api/generating-types

import { Merchant } from "../types";

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      merchants: {
        Row: Merchant; // The data expected from a SELECT statement
        Insert: Omit<Merchant, 'id'>; // The data needed for an INSERT statement
        Update: Partial<Merchant>; // The data needed for an UPDATE statement
      }
      // ... other tables like 'deals', 'documents', etc.
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
